spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentora
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

jwt:
  secret: R5BZsD12xsuHNypY2K/FysErfd5O7GLdr+MetXj1C84=
  expiration: 900000