spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentora
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true